# Generated by Django 3.1.2 on 2020-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Customer name')),
                ('message', models.CharField(max_length=128, verbose_name='Customer name')),
                ('phone_number', models.CharField(max_length=128, verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer request',
                'verbose_name_plural': 'Customer requests',
            },
        ),
    ]
